修改了item1 item2部分翻译
kelthuzadx/EffectiveModernCppChinese pull request #74
Opened 2021-01-30 13:50 UTC by neko-horikawaraiko

2021-01-31 09:08 UTC, kelthuzadx requested changes
感谢修订，原翻译比较脱缰，侧重于“通顺，易于理解”。修订的翻译尊重原文，补充了原翻译中缺少的很多纰漏、样式。有一些风格问题需要稍微修改一下。

2021-01-31 09:08 UTC, kelthuzadx commented on 1.DeducingTypes/item1.md
> +C++98有一套类型推导的规则：这一套用于函数模板。C++11修改了其中的一些规则并增加了两套规则，一套用于`auto`，一套用于`decltype`。C++14扩展了`auto`和`decltype`可能使用的范围。类型推导的广泛应用，让你从拼写那些或明显或冗杂的类型名的暴行中脱离出来。它让C++程序更具适应性，因为在源代码某处修改类型会通过类型推导自动传播到其它地方。但是类型推导也会让代码更
> C++98有一套类型推导的规则：这一套用于函数模板

两个“一套”略显冗余。

2021-01-31 09:08 UTC, kelthuzadx commented on 1.DeducingTypes/item1.md
> +这一章提供了每个C++程序员都应该掌握的知识。它解释了模板类型推导是如何工作的，`auto`是如何依赖类型推导的，以及`decltype`是如何按照它自己那套独特的规则工作的。它甚至解释了你该如何强制编译器使类型推导的结果可视，这能让你确认编译器的类型推导是否按照你期望的那样进行。
> 这一章提供了...知识

不太恰当，不必拘泥于provide的直译。

2021-01-31 14:35 UTC, neko-horikawaraiko commented on 1.DeducingTypes/item2.md
> +**请记住：**
正在修改 后面的会慢慢改过去

2021-01-31 14:36 UTC, neko-horikawaraiko commented on 1.DeducingTypes/item2.md
> +你可能想知道为什么`auto`类型推导和模板类型推导对于花括号有不同的处理方式。我也想知道。哎，我至今没找到一个令人信服的解释。但是规则就是规则，这意味着你必须记住如果你使用`auto`声明一个变量，并用花括号进行初始化，`auto`类型推导总会得出`std::initializer_list`的结果。如果你使用**uniform initialization（花括号的方式进行初始化）**用得很
同样正在修改

2021-01-31 14:41 UTC, neko-horikawaraiko commented on 1.DeducingTypes/item1.md
> +<font size = 5>**情景一：`ParamType`是一个指针或引用，但不是通用引用**</font>
这边因为使用##会在建立pdf书签时自动连接上，我觉得会对书签有些污染所以改成了非标题形式。如果确定我的写法不合适我会在下一版改掉。

2021-02-01 02:14 UTC, kelthuzadx commented on 1.DeducingTypes/item1.md
> +<font size = 5>**情景一：`ParamType`是一个指针或引用，但不是通用引用**</font>
可以修改成更子一级的标题，这样应该就能让这些内容位于当前章节之中。

2021-02-01 06:22 UTC, neko-horikawaraiko commented on 1.DeducingTypes/item1.md
> +<font size = 5>**情景一：`ParamType`是一个指针或引用，但不是通用引用**</font>
好的，我改一下

2021-02-03 14:38 UTC, neko-horikawaraiko commented
回家休息两周，可能会暂停或者慢速提交

2021-02-08 15:25 UTC, kelthuzadx approved these changes

2021-02-08 15:33 UTC, kelthuzadx commented
已经邀请你成为collaborator了，如果你确定改动没有什么问题可以直接向master贡献代码。拿不准的可以拿出来讨论。

感谢贡献～

2021-02-10 09:48 UTC, neko-horikawaraiko commented
我还是先推在这个分支吧，等你再审一遍没什么太大问题再加进master里

2021-02-14 07:13 UTC, merged